name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build on JDK ${{ matrix.java }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: "Cache local Maven repository"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Build"
        run: mvn clean package -B -Dmaven.test.skip=true
      - name: Upload compiled jar
        uses: actions/upload-artifact@v4.0.0
        with:
          name: GriefPrevention
          path: target/GriefPrevention.jar
          
        
